defmodule LangseedWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :langseed

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_langseed_key",
    signing_salt: "rX77hzhl",
    same_site: "Lax"
  ]

  # Redirect www to non-www
  plug :redirect_www

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :langseed,
    gzip: not code_reloading?,
    only: LangseedWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :langseed
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LangseedWeb.Router

  defp redirect_www(%{host: "www." <> host} = conn, _opts) do
    url = "https://#{host}#{conn.request_path}"

    url =
      if conn.query_string != "" do
        url <> "?" <> conn.query_string
      else
        url
      end

    conn
    |> Plug.Conn.put_resp_header("location", url)
    |> Plug.Conn.send_resp(301, "")
    |> Plug.Conn.halt()
  end

  defp redirect_www(conn, _opts), do: conn
end
